/** Liquid Nifty 500 names plus listed ETFs Yahoo Finance serves as NSE `.NS` quotes. */
export const NIFTY_UNIVERSE: { ticker: string; name: string; kind?: "equity" | "etf" }[] = [
  { ticker: "RELIANCE", name: "Reliance Industries" },
  { ticker: "HDFCBANK", name: "HDFC Bank" },
  { ticker: "BHARTIARTL", name: "Bharti Airtel" },
  { ticker: "TCS", name: "Tata Consultancy Services" },
  { ticker: "ICICIBANK", name: "ICICI Bank" },
  { ticker: "SBIN", name: "State Bank of India" },
  { ticker: "INFY", name: "Infosys" },
  { ticker: "BAJFINANCE", name: "Bajaj Finance" },
  { ticker: "HINDUNILVR", name: "Hindustan Unilever" },
  { ticker: "ITC", name: "ITC" },
  { ticker: "LT", name: "Larsen & Toubro" },
  { ticker: "KOTAKBANK", name: "Kotak Mahindra Bank" },
  { ticker: "AXISBANK", name: "Axis Bank" },
  { ticker: "HCLTECH", name: "HCL Technologies" },
  { ticker: "MARUTI", name: "Maruti Suzuki" },
  { ticker: "SUNPHARMA", name: "Sun Pharmaceutical" },
  { ticker: "M&M", name: "Mahindra & Mahindra" },
  { ticker: "ULTRACEMCO", name: "UltraTech Cement" },
  { ticker: "NTPC", name: "NTPC" },
  { ticker: "TITAN", name: "Titan Company" },
  { ticker: "POWERGRID", name: "Power Grid" },
  { ticker: "TATAMOTORS", name: "Tata Motors" },
  { ticker: "BEL", name: "Bharat Electronics" },
  { ticker: "TRENT", name: "Trent" },
  { ticker: "ASIANPAINT", name: "Asian Paints" },
  { ticker: "WIPRO", name: "Wipro" },
  { ticker: "JSWSTEEL", name: "JSW Steel" },
  { ticker: "BAJAJFINSV", name: "Bajaj Finserv" },
  { ticker: "GRASIM", name: "Grasim Industries" },
  { ticker: "ADANIPORTS", name: "Adani Ports" },
  { ticker: "COALINDIA", name: "Coal India" },
  { ticker: "HINDALCO", name: "Hindalco" },
  { ticker: "ONGC", name: "ONGC" },
  { ticker: "NESTLEIND", name: "Nestle India" },
  { ticker: "EICHERMOT", name: "Eicher Motors" },
  { ticker: "TECHM", name: "Tech Mahindra" },
  { ticker: "CIPLA", name: "Cipla" },
  { ticker: "SBILIFE", name: "SBI Life" },
  { ticker: "DRREDDY", name: "Dr. Reddy's" },
  { ticker: "APOLLOHOSP", name: "Apollo Hospitals" },
  { ticker: "HDFCLIFE", name: "HDFC Life" },
  { ticker: "TATACONSUM", name: "Tata Consumer" },
  { ticker: "ADANIENT", name: "Adani Enterprises" },
  { ticker: "BPCL", name: "Bharat Petroleum" },
  { ticker: "HEROMOTOCO", name: "Hero MotoCorp" },
  { ticker: "INDUSINDBK", name: "IndusInd Bank" },
  { ticker: "SHRIRAMFIN", name: "Shriram Finance" },
  { ticker: "BRITANNIA", name: "Britannia" },
  { ticker: "DIVISLAB", name: "Divi's Laboratories" },
  { ticker: "TATAPOWER", name: "Tata Power" },
  { ticker: "BAJAJ-AUTO", name: "Bajaj Auto" },
  { ticker: "HINDZINC", name: "Hindustan Zinc" },
  { ticker: "VEDL", name: "Vedanta" },
  { ticker: "DLF", name: "DLF" },
  { ticker: "LODHA", name: "Macrotech Developers" },
  { ticker: "IRFC", name: "IRFC" },
  { ticker: "PFC", name: "Power Finance Corp" },
  { ticker: "RECLTD", name: "REC" },
  { ticker: "BANKBARODA", name: "Bank of Baroda" },
  { ticker: "PNB", name: "Punjab National Bank" },
  { ticker: "CANBK", name: "Canara Bank" },
  { ticker: "UNIONBANK", name: "Union Bank" },
  { ticker: "IOC", name: "Indian Oil" },
  { ticker: "GAIL", name: "GAIL" },
  { ticker: "ADANIGREEN", name: "Adani Green" },
  { ticker: "ADANIPOWER", name: "Adani Power" },
  { ticker: "JINDALSTEL", name: "Jindal Steel" },
  { ticker: "TATASTEEL", name: "Tata Steel" },
  { ticker: "PIDILITIND", name: "Pidilite" },
  { ticker: "GODREJCP", name: "Godrej Consumer" },
  { ticker: "DABUR", name: "Dabur" },
  { ticker: "MARICO", name: "Marico" },
  { ticker: "HAVELLS", name: "Havells" },
  { ticker: "VOLTAS", name: "Voltas" },
  { ticker: "SIEMENS", name: "Siemens" },
  { ticker: "ABB", name: "ABB India" },
  { ticker: "CGPOWER", name: "CG Power" },
  { ticker: "POLYCAB", name: "Polycab" },
  { ticker: "CUMMINSIND", name: "Cummins India" },
  { ticker: "BOSCHLTD", name: "Bosch" },
  { ticker: "MOTHERSON", name: "Samvardhana Motherson" },
  { ticker: "BALKRISIND", name: "Balkrishna Industries" },
  { ticker: "MRF", name: "MRF" },
  { ticker: "TVSMOTOR", name: "TVS Motor" },
  { ticker: "ASHOKLEY", name: "Ashok Leyland" },
  { ticker: "PERSISTENT", name: "Persistent Systems" },
  { ticker: "LTIM", name: "LTIMindtree" },
  { ticker: "COFORGE", name: "Coforge" },
  { ticker: "MPHASIS", name: "Mphasis" },
  { ticker: "LTTS", name: "L&T Technology" },
  { ticker: "OFSS", name: "Oracle Financial" },
  { ticker: "NAUKRI", name: "Info Edge" },
  { ticker: "ZOMATO", name: "Eternal (Zomato)" },
  { ticker: "PAYTM", name: "One97 (Paytm)" },
  { ticker: "POLICYBZR", name: "PB Fintech" },
  { ticker: "NYKAA", name: "Nykaa" },
  { ticker: "DMART", name: "Avenue Supermarts" },
  { ticker: "MAXHEALTH", name: "Max Healthcare" },
  { ticker: "FORTIS", name: "Fortis Healthcare" },
  { ticker: "AUROPHARMA", name: "Aurobindo Pharma" },
  { ticker: "LUPIN", name: "Lupin" },
  { ticker: "TORNTPHARM", name: "Torrent Pharma" },
  { ticker: "ALKEM", name: "Alkem" },
  { ticker: "BIOCON", name: "Biocon" },
  { ticker: "ZYDUSLIFE", name: "Zydus Lifesciences" },
  { ticker: "ICICIPRULI", name: "ICICI Prudential Life" },
  { ticker: "ICICIGI", name: "ICICI Lombard" },
  { ticker: "CHOLAFIN", name: "Cholamandalam" },
  { ticker: "BAJAJHLDNG", name: "Bajaj Holdings" },
  { ticker: "MUTHOOTFIN", name: "Muthoot Finance" },
  { ticker: "HDFCAMC", name: "HDFC AMC" },
  { ticker: "SBICARD", name: "SBI Cards" },
  { ticker: "FEDERALBNK", name: "Federal Bank" },
  { ticker: "IDFCFIRSTB", name: "IDFC First Bank" },
  { ticker: "HAL", name: "Hindustan Aeronautics" },
  { ticker: "BHEL", name: "BHEL" },
  { ticker: "NHPC", name: "NHPC" },
  { ticker: "NMDC", name: "NMDC" },
  { ticker: "SAIL", name: "SAIL" },
  { ticker: "INDIGO", name: "InterGlobe Aviation" },
  { ticker: "IRCTC", name: "IRCTC" },
  { ticker: "CONCOR", name: "Container Corp" },
  { ticker: "PIIND", name: "PI Industries" },
  { ticker: "UPL", name: "UPL" },
  { ticker: "COROMANDEL", name: "Coromandel" },
  { ticker: "AMBUJACEM", name: "Ambuja Cements" },
  { ticker: "SHREECEM", name: "Shree Cement" },
  { ticker: "DALBHARAT", name: "Dalmia Bharat" },
  { ticker: "ACC", name: "ACC" },
  { ticker: "INDHOTEL", name: "Indian Hotels" },
  { ticker: "JUBLFOOD", name: "Jubilant FoodWorks" },
  { ticker: "PAGEIND", name: "Page Industries" },
  { ticker: "KALYAN", name: "Kalyan Jewellers" },
  { ticker: "DIXON", name: "Dixon Technologies" },
  { ticker: "KAYNES", name: "Kaynes Technology" },
  { ticker: "SOLARINDS", name: "Solar Industries" },
  { ticker: "KEI", name: "KEI Industries" },
  { ticker: "APLAPOLLO", name: "APL Apollo" },
  { ticker: "ASTRAL", name: "Astral" },
  { ticker: "OBEROIRLTY", name: "Oberoi Realty" },
  { ticker: "GODREJPROP", name: "Godrej Properties" },
  { ticker: "PRESTIGE", name: "Prestige Estates" },
  { ticker: "PHOENIXLTD", name: "Phoenix Mills" },
  { ticker: "NIFTYBEES", name: "Nippon India ETF Nifty BeES", kind: "etf" },
  { ticker: "BANKBEES", name: "Nippon India ETF Bank BeES", kind: "etf" },
  { ticker: "JUNIORBEES", name: "Nippon India ETF Junior BeES", kind: "etf" },
  { ticker: "ITBEES", name: "Nippon India ETF IT BeES", kind: "etf" },
  { ticker: "MON100", name: "Motilal Oswal Nasdaq 100 ETF", kind: "etf" },
  { ticker: "GOLDBEES", name: "Nippon India ETF Gold BeES", kind: "etf" },
  { ticker: "SETFGOLD", name: "SBI Gold ETF", kind: "etf" },
  { ticker: "GOLDSHARE", name: "UTI Gold ETF", kind: "etf" },
  { ticker: "SILVERBEES", name: "Nippon India Silver ETF", kind: "etf" },
];

export const METAL_ETFS: Record<"gold" | "silver" | "copper", { ticker: string; name: string }[]> = {
  gold: [
    { ticker: "GOLDBEES", name: "Nippon India ETF Gold BeES" },
    { ticker: "SETFGOLD", name: "SBI Gold ETF" },
    { ticker: "GOLDSHARE", name: "UTI Gold ETF" },
  ],
  silver: [{ ticker: "SILVERBEES", name: "Nippon India Silver ETF" }],
  copper: [],
};

export const METAL_SPECS = [
  {
    code: "gold" as const,
    name: "Gold",
    yahoo: "GC=F",
    venue: "COMEX → INR (MCX-style 10g)",
    unit: "₹ / 10g",
    convert: (usdPerOz: number, usdInr: number) =>
      (usdPerOz / 31.1034768) * 10 * usdInr,
  },
  {
    code: "silver" as const,
    name: "Silver",
    yahoo: "SI=F",
    venue: "COMEX → INR (MCX-style kg)",
    unit: "₹ / kg",
    convert: (usdPerOz: number, usdInr: number) =>
      (usdPerOz / 31.1034768) * 1000 * usdInr,
  },
  {
    code: "copper" as const,
    name: "Copper",
    yahoo: "HG=F",
    venue: "COMEX → INR (per kg)",
    unit: "₹ / kg",
    convert: (usdPerLb: number, usdInr: number) => usdPerLb * 2.20462 * usdInr,
  },
];
